# Generated by Django 5.2.8 on 2025-11-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo (HTML)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de postagem')),
            ],
        ),
    ]
