# Generated by Django 5.2.8 on 2025-12-06 03:18
from django.db import migrations
from django.core.management import call_command


def load_initial_data(apps, schema_editor):
    # Vai procurar o arquivo em blog/fixtures/initial_data.json
    call_command('loaddata', 'initial_data.json')


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_favorites'),  # deixa como estava no arquivo
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]

